Repository DumindUdara/Travel-Agency, pull requests merged in 2023-10, with the labels that each got.

#1 update-01
  index.html
Labels: hacktoberfest

#3 Create README.md
  README.md
Labels: hacktoberfest

#4 update
  README.md
Labels: hacktoberfest

#5 Update 3
  about.html
  contact.html
  elements.html
  index.html
Labels: hacktoberfest

#7 Update 1
  elements.html
Labels: hacktoberfest

#9 Update README.md
  README.md
Labels: hacktoberfest

#10 Readme
  README.md
Labels: hacktoberfest

#12 new
  about.html
  contact.html
  elements.html
  index.html
Labels: hacktoberfest

#15 Documentation update
  README.md
Labels: documentation, hacktoberfest

#17 fix: change contact us target from booking.html into contact.html
  about.html
  elements.html
  index.html
  services.html
Labels: bug, hacktoberfest

#18 Update about html
  about.html
Labels: hacktoberfest

#19 Update contact.html
  contact.html
Labels: hacktoberfest

#20 update elements.html
  elements.html
Labels: hacktoberfest

#23 Update about.html
  about.html
Labels: hacktoberfest

#24 Update about,html
  about.html
Labels: hacktoberfest

#25 Update about.html
  about.html
Labels: hacktoberfest

#26 Update contact.html
  contact.html
Labels: hacktoberfest

#31 Janith sheshan edit
  about.html
  services.html
Labels: hacktoberfest

#32 Update about.html
  about.html
Labels: hacktoberfest

#33 Update contact.html
  contact.html
Labels: hacktoberfest

#34 Update index.html
  index.html
Labels: hacktoberfest

#35 Update index.html
  index.html
Labels: hacktoberfest

#44 update
  about.html
  contact.html
  index.html
  services.html
Labels: hacktoberfest, open source

#45 Update
  about.html
  contact.html
  index.html
  services.html
Labels: open source

#46 update
  about.html
  contact.html
  index.html
  services.html
Labels: bug, hacktoberfest, open source
